### ISSUE TITLE
subprocess.call and mlflow.log_artifact checks inconsistent in linter

### ISSUE THREAD

**Issue by Imipenem** [mlf-core/mlf-core#171]
**Describe the bug**

* ` f'subprocess.call([\'conda\', \'env\', \'export\', \'--name\', \'{self.project_slug_no_hyphen}\'], stdout=conda_env_filehandler)',`
* ` f'mlflow.log_artifact(f\'{{reports_output_dir}}/{self.project_slug_no_hyphen}_conda_environment.yml\', artifact_path=\'reports\')'`

Those two linting functions caused the template create WFs (and sometimes even local) to fail

**Expected behavior**

They should pass. We should discuss why they fail and how to fix!
So currently they are outcommented!

**Comment by Zethson** [comment]
@Emiller88 the linter should for all templates just check that these methods are called in the templates. Ideally you just need to add those two lines to the linter checks.

I won't explain the original issue here since I just expect it to work :) If it still doesn't I will reassign @Imipenem and me.
